#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1

if [ -x $HOME/.config/bspwm/dual-monitor ]; then
        $HOME/.config/bspwm/dual-monitor
fi

$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/startup &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor eDP -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
