#!/bin/bash
ext_mon=$(xrandr --query | grep 'HDMI-A-0')

if [[ $ext_mon = *connected* ]]; then
	xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rate 120.00 --rotate normal --left-of eDP
fi
